### ISSUE TITLE
Switch from `aioredis` to `redis`

### ISSUE THREAD

**Issue by applied-mathematician** [long2ice/fastapi-admin#109]
Code from `aioredis` was incorporated into the official `redis` package in v4.2 to adopt the async support.  As a result, `aioredis` will no longer be well maintained.  The switch to `redis` will be relatively painless since the functions+parameters are basically the same.

References:

- https://github.com/aio-libs/aioredis-py#-aioredis-is-now-in-redis-py-420rc1-
- https://github.com/redis/redis-py#python-notice

**Comment by long2ice** [comment]
Done
