### ISSUE TITLE
Postgresql Problem

### ISSUE THREAD

**Issue by carlosnutual** [long2ice/fastapi-admin#110]
Hello, I am using trying to connect PostgreSQL on my fastapi-admin project.
Is this possible? I'm getting an error about timeout:

 File "/usr/local/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
 raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

On another hand, I would like to connect the project with a custom PostgreSQL DB. Is there any way to do it using my own tables?

![image](https://user-images.githubusercontent.com/98756380/178712576-ff894acc-764d-4e3d-8e12-3ff68764ca22.png)

**Comment by long2ice** [comment]
Just set `DATABASE_URL` env

**Comment by carlosnutual** [comment]
I had an issue in my docker image. Solved. Thank you
