### ISSUE TITLE
Problem to connect Serverless Database with Redis API 

### ISSUE THREAD

**Issue by carlosnutual** [long2ice/fastapi-admin#111]
Hello,
I'm trying to connect my fastapi admin app with a Serverless Database with Redis API (upstash). If I execute uvicorn examples.main:app_  instead of docker-compose, it works and connect properly to redis but when I use docker-compose I got the following error: **aioredis.exceptions.ConnectionError: Error connecting to localhost:6379**
Why is trying to connect with localhost when I specified in my .env the url of my redis serverless?
Any clue what is going on? 

Regards

**Comment by long2ice** [comment]
Try to set `REDIS_URL` env

**Comment by carlosnutual** [comment]
It is already set. The problem is the app is trying to connect with localhost:6379 for some reason. As I said before this only happens with docker compose, if I execute as uvicorn examples.main:app_ it works properly
