### ISSUE TITLE
大哥，搜索怎么定义

### ISSUE THREAD

**Issue by npc7** [long2ice/fastapi-admin#12]
文档中：
搜索
定义 menu.search_fields会渲染出一个搜索框。

Xlsx 导出
FastAPI-admin 可导出 xlsx 文件，只需在menu设置export=True。

代码中 需要怎么定义？
menu = Menu(
               ...
                search_field="",
                export=True,
            )
我这样写不行

**Comment by long2ice** [comment]
指定需要筛选的字段

**Comment by npc7** [comment]
找到了 谢谢大哥
