### ISSUE TITLE
在example/main.py中增加了一个 Menu，如何才能在前端显示

### ISSUE THREAD

**Issue by liuqlive** [long2ice/fastapi-admin#13]
1.在models.py中追加了 class Order的定义；数据库中通过sql创建了Order表。
2.在main.py中追加了如下的部分
Menu(
                            name="Order",
                            url="/rest/Order",
                            icon="fa fa-gear",
                            import_=True,
                            search_fields=("userid",),
                         ),
3.重新打包了 docker-compose up -d --build  
4.前端也重新 build了

反复刷新，前端都不能看见 Order节点。 特意去掉了 Config Menu，从前端确实看不见了。

**Comment by liuqlive** [comment]
是加在children中的，添加后的实际结果如下：
children=[
                        Menu(
                            name="Category",
                            url="/rest/Category",
                            icon="fa fa-list",
                            search_fields=("slug",),
                        ),
                        Menu(
                            name="Config",
                            url="/rest/Config",
                            icon="fa fa-gear",
                            import_=True,
                            search_fields=("key",),
                        ),
                        Menu(
                            name="Order",
                            url="/rest/Order",
                            icon="fa fa-table",
                            import_=True,
                            search_fields=("userid",),
                         ),
                        Menu(
                            name="Product",
                            url="/rest/Product",
                            icon="fa fa-table",
                            search_fields=("name",),
                        ),
会不会和 tortoise-orm的order表 没有映射上的缘故？

**Comment by long2ice** [comment]
那应该是权限问题，你要加上权限

**Comment by liuqlive** [comment]
is_superuser的情况下，可以看见了。多谢。
