### ISSUE TITLE
使用文档太少

### ISSUE THREAD

**Issue by littleforce163** [long2ice/fastapi-admin#15]
介绍资料有点少，代码运行不起来

**Comment by long2ice** [comment]
参考example

**Comment by littleforce163** [comment]
想比较而言，fastapi的文档说明很到位，一步步可以得到预期结果
如果代码中对外不有依赖，比如数据库，会写一段伪操作来代替，整体过程非常清晰。
希望可以借鉴。
本项目不容易理解有哪些功能，都该怎么用。
