### ISSUE TITLE
Translations are not loaded correctly

### ISSUE THREAD

**Issue by iakov-kaiumov** [long2ice/fastapi-admin#151]
Hi, I have a question.

I tried to setup admin panel according to the example and everything works now except of translations. I added templates and they work as expected.

I check function `_` (`from fastapi_admin.i18n import _`) and it also returns empty strings. 
<img width="581" alt="image" src="https://github.com/fastapi-admin/fastapi-admin/assets/29120192/926454d8-392b-43a6-9eda-1be3f00c1047">

**Comment by nb-programmer** [comment]
I identified the reason that the author has not pushed compiled locale (.mo files for i18n) in the latest package version, only the human-readable .po files are there. The `Translations.load` function tries to find these but fails, so sticks to `NullTranslations` as fallback.
I can see that the Makefile has a `compile` recipe which does this, but for some reason it isn't present in the pypi package.
@fastapi-admin will need to rebuild and republish with the `.mo` files for this to work.

Edit:
https://github.com/fastapi-admin/fastapi-admin/blob/ebea3bf71689caa583fe55aa25db899cf8eeae31/fastapi_admin/i18n.py#L8C1-L13C2

These lines try to load translations already present in [fastapi-admin/fastapi-admin/tree/dev/fastapi_admin/locales](https://github.com/fastapi-admin/fastapi-admin/tree/ebea3bf71689caa583fe55aa25db899cf8eeae31/fastapi_admin/locales)
They are present here in the repo, but when installing (with `pip install fastapi-admin`), they are not present.

Solution for now would be to install from git:
`pip install git+https://github.com/fastapi-admin/fastapi-admin.git`

**Comment by nb-programmer** [comment]
Update: Just realized the last release on PyPI is on Jun 8, 2022, so it's outdated.
Best to just use the github version directly

**Comment by iakov-kaiumov** [comment]
@nb-programmer Thanks!

**Comment by iakov-kaiumov** [comment]
One should use correct version from git: pip install git+https://github.com/fastapi-admin/fastapi-admin.git
