### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by littleforce163** [long2ice/fastapi-admin#16]
can't execute:  python setup.py install
@https://fastapi-admin-docs.long2ice.cn/get_start.html#run-example-local

**Comment by long2ice** [comment]
看README，文档不是最新的

**Comment by littleforce163** [comment]
readme：运行样例第三布
3.执行python setup.py install。

**Comment by long2ice** [comment]
https://github.com/long2ice/fastapi-admin/blob/dev/README.md

**Comment by littleforce163** [comment]
在pycharm里不能运行吗，看链接要用docker

**Comment by long2ice** [comment]
可以，用docker只是为了更快跑起来demo

**Comment by littleforce163** [comment]
1. 仿照dockerfile, 安装了环境，
2. os.environ["DATABASE_URL"] = "mysql://root:123456@192.168.1.4:3306/fastapi_admin"
    由于mysql8中不能支持”-“，所以换成了下划线
3. mysql8建库fastapi_admin，然后把example.sql放到mysql8中执行，全部导入。

最后，执行examples/main.py时出错

```
INFO:     Started server process [86443]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
**INFO:uvicorn.error:Application startup complete.**
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
```

**Comment by littleforce163** [comment]
pycharm中debug，发现不会运行startup函数

@app.on_event("startup")
async def start_up():
    await admin_app.init(
