### ISSUE TITLE
默默潜水看了你这个项目一段时间了

### ISSUE THREAD

**Issue by zky001** [long2ice/fastapi-admin#2]
不知道有没有兴趣我们一起开发
我现在做了一个平台也是基于fastapi的
咱们一起做吧

**Comment by zky001** [comment]
把fastapi-admin这块的功能、和flask-admin、go-admin比较比较  做个方便快捷的脚手架出来

**Comment by long2ice** [comment]
具体如何做？我其实不擅长前端开发，前端部分都是从另一个项目移植的。

**Comment by long2ice** [comment]
这个项目其实大部分按照Django admin来的。

**Comment by zky001** [comment]
> 具体如何做？我其实不擅长前端开发，前端部分都是从另一个项目移植的。

可以用vue+jQuery做前端  我可以完成一部分前端工作

**Comment by zky001** [comment]
> 这个项目其实大部分按照Django admin来的。

可以看看Django xadmin

**Comment by CL545740896** [comment]
加油加油

**Comment by CL545740896** [comment]
怎么进入演示的后台

**Comment by long2ice** [comment]
？有在线地址和测试账号，可能加载有点慢

**Comment by CL545740896** [comment]
> ？有在线地址和测试账号，可能加载有点慢

![image](https://user-images.githubusercontent.com/27679586/80555351-9bff7800-8a02-11ea-8c61-2f70a5b9e940.png)
没k看到登录界面

**Comment by long2ice** [comment]
额，貌似有点问题，https://fastapi-admin.long2ice.cn/#/login，你直接访问这个

**Comment by zky001** [comment]
> 额，貌似有点问题，https://fastapi-admin.long2ice.cn/#/login，你直接访问这个

定位一下问题在哪里哇  性能瓶颈是在哪里？

**Comment by long2ice** [comment]
已经解决了，后台管理项目没必要考虑性能问题吧，最大的可能就是数量量过大导致每次count很慢。

**Comment by zky001** [comment]
> 已经解决了，后台管理项目没必要考虑性能问题吧，最大的可能就是数量量过大导致每次count很慢。

比如页面的logo  我做个定制化接口如何？<img src="https://github.com/long2ice/fastapi-admin/raw/master/front/static/img/logo.png" class="site-logo img-fluid">

**Comment by long2ice** [comment]
这个是可配置的，具体可参考[examples](https://github.com/long2ice/fastapi-admin/tree/master/examples)。
关闭本issue，有其他问题可新建issue。

**Comment by zky001** [comment]
> 这个是可配置的，具体可参考[examples](https://github.com/long2ice/fastapi-admin/tree/master/examples)。
> 关闭本issue，有其他问题可新建issue。

你前端可以用Stisla
