### ISSUE TITLE
Can you use SQLAlchemy?

### ISSUE THREAD

**Issue by DImasBo** [long2ice/fastapi-admin#24]
Hi, Can you use SQLAlchemy?

**Comment by long2ice** [comment]
No, which doesn't support asyncio

**Comment by nikhilakki** [comment]
how about [databases](https://github.com/encode/databases)?

**Comment by long2ice** [comment]
Now only support tortoise-orm

**Comment by anudeepsamaiya** [comment]
I am more than willing to help here, sqlalchemy has large amount of developers who can benefit with this. @long2ice @nikhilakki what are your thoughts?

**Comment by long2ice** [comment]
Consider but no plan recently

**Comment by niakki** [comment]
> I am more than willing to help here, sqlalchemy has large amount of developers who can benefit with this. @long2ice @nikhilakki what are your thoughts?

Looks like Async IO is now supported natively by [SQLAlchemy](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html). I can see how it could help projects already using SQLAlchemy. 

@long2ice do you accept PRs?

**Comment by nikhilakki** [comment]
> I am more than willing to help here, sqlalchemy has large amount of developers who can benefit with this. @long2ice @nikhilakki what are your thoughts?

Looks like Async IO is now supported natively by [SQLAlchemy](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html). I can see how it could help projects already using SQLAlchemy.

@long2ice do you accept PRs?
