### ISSUE TITLE
admin/login POST does not work

### ISSUE THREAD

**Issue by mg64ve** [long2ice/fastapi-admin#25]
Hello, 
nice project and thanks for sharing.
I have successfully deployed and it seems everything is working.
I can use the followig command:

`curl -X GET "http://192.168.1.75:8000/admin/site" -H  "accept: application/json"`

and get a proper result.
But if I use the following:

`curl -X POST "http://192.168.1.75:8000/admin/login" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"username\":\"marco\",\"password\":\"123456\"}"`

I am getting:

`{"msg":"Not Found"}`

which I don't think it is correct.
In docker container "fastapi-admin" logs I am finding:

`INFO:     192.168.1.111:41788 - "POST /admin/login HTTP/1.1" 404 Not Found`

**Comment by long2ice** [comment]
You should create superuser first by run `fastapi-admin -c config.TORTOISE_ORM createsuperuser`

**Comment by mg64ve** [comment]
Thanks for your reply @long2ice 
If I execute this command:

`echo "select id,username,is_superuser from user;"  | docker-compose exec -T mysql mysql -uroot -p123456 fastapi-admin`

I can see there is already one superuser:

```
id	username	is_superuser
1	long2ice	1
2	admin	0
3	test	0
```

However I can't find "fastapi-admin" command, may be you mean fastapi_adim/cli.py ?
If I execute:

`python3 fastapi_admin/cli.py -V`

I am not getting any result.
Could you please give me more information?
Thanks.

**Comment by long2ice** [comment]
`fastapi-admin` will create after you install fastapi-admin by pip

**Comment by mg64ve** [comment]
Ok @long2ice 
But what is config.TORTOISE_ORM ?
Because executing the following command:

`fastapi-admin -c config.TORTOISE_ORM createsuperuser -u marco`

I am getting:

`ModuleNotFoundError: No module named 'config'`

while executing:

`fastapi-admin -V`

I am now getting:

`fastapi-admin version, 0.3.3`

**Comment by long2ice** [comment]
Which is your tortoise config location, and is a dict

**Comment by mg64ve** [comment]
thanks @long2ice 
For the example in this repository, where is this file ?
I have tried to create a file with the following content:

```
TORTOISE_ORM = {
    "connections": {"default": "mysql://root:123456@mysql:3306/fastapi-admin"},
    "apps": {"models": {"models": ["examples.models"], "default_connection": "default"}},
}
```

But I am getting the following error:

```
ModuleNotFoundError: No module named 'tortoise_orm'
```

**Comment by mg64ve** [comment]
Ok I put the following:

```
TORTOISE_ORM = {
    "connections": {"default": "mysql://root:123456@mysql:3306/fastapi-admin"},
    "apps": {"models": {"models": ["examples.models"], "default_connection": "default"}},
}
```

in settings.py in examples directory, then from the example directory I issues the command:

```
fastapi-admin -c settings.TORTOISE_ORM createsuperuser --user marco
```
But I am getting the following prompt and error:

![image](https://user-images.githubusercontent.com/22278227/103372316-f725c500-4ad1-11eb-85d3-d212515bc58f.png)

and again is prompting me for user name.
Is this process correct @long2ice ? What is wrong?
Kindly let me know. Thanks.

**Comment by mg64ve** [comment]
Sorry @long2ice did you have a look to my question?

**Comment by long2ice** [comment]
set --user=User

**Comment by mg64ve** [comment]
Hi @long2ice 
I am having the same result:

![image](https://user-images.githubusercontent.com/22278227/103617666-f1dfd480-4f2e-11eb-8162-def080e744cb.png)

what is the issue?

**Comment by long2ice** [comment]
--user means `User` model, not username, usually is `User`

**Comment by mg64ve** [comment]
Ok @long2ice 
Just created the user but I am still not able to get the login page:

![image](https://user-images.githubusercontent.com/22278227/103622877-9534e780-4f37-11eb-945c-02d6db8e3aec.png)

I am getting "detail": "Not Found"

**Comment by long2ice** [comment]
see https://github.com/long2ice/restful-admin
