### ISSUE TITLE
Uvloop dependency

### ISSUE THREAD

**Issue by mosheduminer** [long2ice/fastapi-admin#4]
Hi, I discovered this fantastic project of yours, and would like to use it in my project. However, when I try to install `fastapi-admin`, I discovered that `uvloop` is a required dependency. As I understand, it is better to use `uvloop` with `FastAPI`, however `uvloop` is not available on windows, so it would be better, if possible, to remove `uvloop` from the required dependencies. Since I am using windows as my dev machine, I would appreciate it if this could be changed.

**Comment by long2ice** [comment]
That's reasonable and I will fix that later in version 0.2.8.
And thanks your donation for my project, that's a great encourage for my opensource work.😁
