### ISSUE TITLE
can´t find setup.py

### ISSUE THREAD

**Issue by xbln** [long2ice/fastapi-admin#6]
Hi Sir,
I don´t understand step 3 of that local example. There is no setup.py, the command "python setup.py install" fails.

**Comment by long2ice** [comment]
You can use [poetry](https://github.com/python-poetry/poetry) and `poetry install`, sorry the docs is old and I forgot to update.

**Comment by xbln** [comment]
Thanks for your reply. Anyway, also with poetry I run into errors:

Traceback (most recent call last):
  File "/usr/lib/command-not-found", line 28, in <module>
    from CommandNotFound import CommandNotFound
  File "/usr/lib/python3/dist-packages/CommandNotFound/CommandNotFound.py",
line 19, in <module>
    from CommandNotFound.db.db import SqliteDatabase
  File "/usr/lib/python3/dist-packages/CommandNotFound/db/db.py", line 5,
in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Best

Martin Esche
martin.esche@gmx.de
Mobile +49 171 4103644


Am Do., 9. Juli 2020 um 03:24 Uhr schrieb long2ice <notifications@github.com

**Comment by long2ice** [comment]
How do you install poetry?

**Comment by xbln** [comment]
After setting my PATH variable to Poetry's bin directory, installing venv
and moving to the fastapi-admin directory, Poetry installed the packages.

The command:"env
DATABASE_URL=mysql://root:SecretPw0!@localhost:3306/fastapi-admin
PYTHONPATH=./ python3 examples/main.py" failed with
-bash: !@localhost: event not found

I added hyphens and changed the command to "env
DATABASE_URL='mysql://root:SecretPw0!@localhost:3306/fastapi-admin'
PYTHONPATH=./ python3 examples/main.py"  which returned

Traceback (most recent call last):
  File "examples/main.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'

I am not a complete newby, but I have problems with your instructions. It
would be nice to make them somehow more precise. It would be a pity if only
experts were able to use your work.

Best

Martin
martin.esche@gmx.de
Mobile +49 171 4103644


Am Do., 9. Juli 2020 um 12:35 Uhr schrieb long2ice <notifications@github.com

**Comment by long2ice** [comment]
Did you install dependencies by `poetry install`?

**Comment by xbln** [comment]
Yes, see the terminal log.


poetry install
The virtual environment found in
/home/pydev/.cache/pypoetry/virtualenvs/fastapi-admin-dIsiRpb--py3.8 seems
to be broken.
Recreating virtualenv fastapi-admin-dIsiRpb--py3.8 in
/home/pydev/.cache/pypoetry/virtualenvs/fastapi-admin-dIsiRpb--py3.8
Installing dependencies from lock file

Package operations: 53 installs, 0 updates, 0 removals

  - Installing pycparser (2.20)
  - Installing pyparsing (2.4.7)
  - Installing six (1.15.0)
  - Installing attrs (19.3.0)
  - Installing cffi (1.14.0)
  - Installing colorama (0.4.3)
  - Installing more-itertools (8.4.0)
  - Installing packaging (20.4)
  - Installing pluggy (0.13.1)
  - Installing py (1.9.0)
  - Installing wcwidth (0.2.5)
  - Installing apipkg (1.5)
  - Installing cryptography (2.9.2)
  - Installing pytest (5.4.3)
  - Installing aiosqlite (0.13.0)
  - Installing appdirs (1.4.4)
  - Installing click (7.1.2)
  - Installing execnet (1.7.1)
  - Installing h11 (0.9.0)
  - Installing httptools (0.1.1)
  - Installing iso8601 (0.1.12)
  - Installing markupsafe (1.1.1)
  - Installing mccabe (0.6.1)
  - Installing pathspec (0.8.0)
  - Installing pycodestyle (2.6.0)
  - Installing pydantic (1.5.1)
  - Installing pyflakes (2.2.0)
  - Installing pymysql (0.9.2)
  - Installing pypika (0.37.15)
  - Installing pytest-forked (1.2.0)
  - Installing regex (2020.6.8)
  - Installing starlette (0.13.4)
  - Installing toml (0.10.1)
  - Installing typed-ast (1.4.1)
  - Installing typing-extensions (3.7.4.2)
  - Installing uvloop (0.14.0)
  - Installing websockets (8.1)
  - Installing aiomysql (0.0.20)
  - Installing bcrypt (3.1.7)
  - Installing black (19.10b0)
  - Installing fastapi (0.58.1)
  - Installing flake8 (3.8.3)
  - Installing isort (5.0.3)
  - Installing jinja2 (2.11.2)
  - Installing passlib (1.7.2)
  - Installing prompt-toolkit (3.0.5)
  - Installing pyjwt (1.7.1)
  - Installing pytest-xdist (1.32.0)
  - Installing python-dotenv (0.14.0)
  - Installing python-rapidjson (0.9.1)
  - Installing tortoise-orm (0.16.13)
  - Installing uvicorn (0.11.5)
  - Installing xlsxwriter (1.2.9)
  - Installing fastapi-admin (0.2.9)

pydev@v2202005108092117303:~/fastapi-admin$ env
DATABASE_URL=mysql://root:SecretPw0!@localhost:3306/fastapi-admin
PYTHONPATH=./ python3 examples/main.py
-bash: !@localhost: event not found

pydev@v2202005108092117303:~/fastapi-admin$ env
DATABASE_URL='mysql://root:SecretPw0!@localhost:3306/fastapi-admin'
PYTHONPATH=./ python3 examples/main.py

Traceback (most recent call last):
  File "examples/main.py", line 3, in <module>
    import uvicorn
ModuleNotFoundError: No module named 'uvicorn'


Best

Martin
martin.esche@gmx.de
Mobile +4 171 4103644


Am Do., 9. Juli 2020 um 16:11 Uhr schrieb long2ice <notifications@github.com

**Comment by long2ice** [comment]
poetry auto create virtualenvs, so you need run `env
DATABASE_URL='mysql://root:SecretPw0!@localhost:3306/fastapi-admin'
PYTHONPATH=./ poetry run python3 examples/main.py`

**Comment by xbln** [comment]
Yes, thank you, it works!

Best

Martin
martin.esche@gmx.de
Mobile +49 171 4103644


Am Do., 9. Juli 2020 um 16:40 Uhr schrieb long2ice <notifications@github.com

**Comment by xbln** [comment]
Thank you, it workd!
