### ISSUE TITLE
windows 怎么办？

### ISSUE THREAD

**Issue by gcshine** [long2ice/fastapi-admin#7]
安装依赖时报错 
RuntimeError: uvloop does not support Windows at the moment

**Comment by long2ice** [comment]
你装的版本是多少，uvloop是可选依赖

**Comment by gcshine** [comment]
安装的uvloop 是 0.14.0 ，我怎么能把这个注释掉呢？

**Comment by long2ice** [comment]
fastapi-admin的版本

**Comment by gcshine** [comment]
fastapi-admin是 0.2.8

**Comment by long2ice** [comment]
那不应该，你直接不安装uvloop试试

**Comment by gcshine** [comment]
我下载的dev，不是master，有影响吗？

**Comment by long2ice** [comment]
没有

**Comment by gcshine** [comment]
ok，我再试试看，3Q

**Comment by gcshine** [comment]
(base) c:\fastapi-admin-dev>python examples/main.py
Traceback (most recent call last):
  File "examples/main.py", line 10, in <module>
    from fastapi_admin.depends import get_model
ModuleNotFoundError: No module named 'fastapi_admin'

(base) c:\fastapi-admin-dev>pip install fastapi_admin
Collecting fastapi_admin
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017C681B1518>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/ce/a8/d142046ded06157bcaa4423a1d7a7e5c423e1a5c3bb56fc1a06a928c5f24/fastapi_admin-0.2.8-py3-none-any.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017C681B1D68>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/ce/a8/d142046ded06157bcaa4423a1d7a7e5c423e1a5c3bb56fc1a06a928c5f24/fastapi_admin-0.2.8-py3-none-any.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x0000017C681B1668>, 'Connection to files.pythonhosted.org timed out. (connect timeout=15)')': /packages/ce/a8/d142046ded06157bcaa4423a1d7a7e5c423e1a5c3bb56fc1a06a928c5f24/fastapi_admin-0.2.8-py3-none-any.whl

**Comment by gcshine** [comment]
无法安装fastapi-admin

**Comment by long2ice** [comment]
换一个镜像源

**Comment by gcshine** [comment]
from fastapi_admin.models import AbstractUser
ImportError: cannot import name 'AbstractUser' from 'fastapi_admin.models' (C:\ProgramData\Anaconda3\lib\site-packages\fastapi_admin\models.py)

我查看了一下确实没有这个AbstractUser类，只有User类

**Comment by gcshine** [comment]
解决了，从阿里云安装的镜像源安装的文件没有这个类，我把下载的最新代码替换了一下好了

**Comment by long2ice** [comment]
嗯
