### ISSUE TITLE
How to deploy FastAPI Admin panel?

### ISSUE THREAD

**Issue by m-peko** [long2ice/fastapi-admin#75]
Hi there,

I was wondering how I can deploy this admin panel. Can you please describe it to me?

Thanks and regards

**Comment by long2ice** [comment]
Did you see docs?

**Comment by m-peko** [comment]
You mean this page https://fastapi-admin.github.io/#run-examples-in-local?

**Comment by long2ice** [comment]
Yes, `fastapi-admin` is just a package, you can deploy it like `fastapi
`
