### ISSUE TITLE
Pro 版本 demo。 无法登录

### ISSUE THREAD

**Issue by ghost** [long2ice/fastapi-admin#87]
Pro 版本 demo。

用户名： admin
密码： 123456
![image](https://user-images.githubusercontent.com/55523175/134802911-6f0be631-6fb7-40c2-8d61-2d041376988e.png)

**Comment by long2ice** [comment]
需要提供自己的google recaptcha配置，或者不启用，另外Pro的问题请发到Pro仓库。
