### ISSUE TITLE
Version pro: I can't find the CAPTCHA...

### ISSUE THREAD

**Issue by Abeautifulsnow** [long2ice/fastapi-admin#97]
I attempted to login fastapi-admin on pro version, but I found there was no CAPTCHA showing on the login page.

![image](https://user-images.githubusercontent.com/28704977/142557545-bb50d98e-cc57-4b19-a973-77e9a15ac0b0.png)

Was this a bug? Or I missed something?

**Comment by long2ice** [comment]
Fixed it
